### ISSUE TITLE
Feature Request: Use microphone as audio source

### ISSUE THREAD

**Issue by darkoverlordofdata** [grame-cncm/faust-web-component#3]
Maybe this is already available and I don't know how to do it. I would like to use the microphone as an audio source. I have a guitar amplifier prototype working in the ide, and I want it to be stand alone. Plus your widget gives me a better ux. But the generated sample uses an audio file. I would like to use the microphone.

Is this available, or could this be a future feature?

**Comment by sletz** [comment]
When the DSP has inputs, and when you compile/activate, the machine audio input is activated, see the screenshot: 
<img width="1440" alt="Capture d’écran 2024-04-01 à 08 43 43" src="https://github.com/grame-cncm/faust-web-component/assets/1430487/1496a712-081d-40b3-9d75-d1e7207e7a87">

**Comment by darkoverlordofdata** [comment]
Great. Thanks!
